spring:
  liquibase:
    change-log: classpath:db/db.changelog-root.yml
    url: jdbc:postgresql://localhost:5432/assignment-product
    user: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/assignment-product
    username: postgres
    password: postgres

hnb:
  services:
    config:
      serverAddress: https://api.hnb.hr/tecajn-eur
      currencyPath: /v3
      currencyName: valuta
      currencyValue: DKK