server:
  port: 8888

spring:
  profiles:
    active: local
  webflux:
    base-path: /assignment-product-service

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    liquibase: DEBUG
    LiquibaseSchemaResolver: DEBUG

springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html