spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/assignment-product
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

hnb:
  services:
    config:
      serverAddres: https://api.hnb.hr/tecajn-eur/v3
      currency: valuta
      value: DKK